# Load antidote from brew installation
source $(brew --prefix)/opt/antidote/share/antidote/antidote.zsh
antidote load


# Disable flow control commands (keeps C-s from freezing everything)
stty start undef
stty stop undef

# Allow [ or ] whatever you want
unsetopt nomatch

## Command history configuration
# Set history file location if not already set
if [ -z "$HISTFILE" ]; then
  HISTFILE="$HOME/.zsh_history"
fi

# Configure history size limits
HISTSIZE=50000
SAVEHIST=50000

# History options
setopt extended_history        # Record timestamp and duration of commands
setopt hist_expire_dups_first  # Delete duplicates first when HISTFILE size exceeds HISTSIZE
setopt hist_ignore_dups        # Don't record duplicated commands
setopt hist_ignore_space       # Don't record commands starting with a space
setopt hist_verify             # Show command with history expansion before running it
setopt inc_append_history      # Add commands to HISTFILE in order of execution
setopt share_history           # Share command history between sessions

# Standardized VISUAL and EDITOR environment variables
export VISUAL=vim
export EDITOR="$VISUAL"

# Extra paths
export PATH=$HOME/bin:/usr/local/bin:$PATH

# Set UTF-8 locale
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Sourcing of other files
source $HOME/.laptop/dotfiles/zsh/aliases
source $HOME/.laptop/dotfiles/zsh/functions

# Load rbenv
eval "$(rbenv init -)"

export PATH="$HOME/.local/bin:$PATH"
eval "$(mise activate zsh)"

# Elixir Phoenix config
export PATH=$HOME/.local/share/mise/installs/erlang/28.3/erts-16.2/bin:$PATH
export PATH=$HOME/.local/share/mise/installs/elixir/1.19.4-otp-28/bin:$PATH

# opencode
export PATH=/Users/javier/.opencode/bin:$PATH
