#!/bin/sh

# Install brew package helper
install_brew_package () {
  if ! brew list | grep -q "$1" >/dev/null 2>&1
  then
    echo "🚀 Installing $1."
    brew install "${2:-$1}" # If a second argument is provided, use it as the package name
    echo "✓ $1 is installed."
  else
    echo "✓ $1 is already installed."
  fi
}

# Check if Homebrew is installed, then install if it isn't
if ! command -v brew >/dev/null 2>&1; then
    echo "🚀 Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    echo "✓ Homebrew is installed."
else
    echo "✓ Homebrew is already installed."
fi

# Install packages
echo "📝 Check for packages installation."
install_brew_package 'git'
install_brew_package 'antidote'
install_brew_package 'lazygit' 'jesseduffield/lazygit/lazygit'
install_brew_package 'rbenv'
install_brew_package 'delta'
install_brew_package 'bat'

echo "🔄 Updating homebrew."
brew update
brew upgrade

# Clean and link dotfiles
rm -f "$HOME/.gemrc"
rm -f "$HOME/.gitconfig"
rm -f "$HOME/.gitignore"
rm -f "$HOME/.vimrc"
rm -f "$HOME/.zshrc"
rm -f "$HOME/.zsh_plugins.txt"
ln -s "$PWD/dotfiles/gemrc" "$HOME/.gemrc"
ln -s "$PWD/dotfiles/gitconfig" "$HOME/.gitconfig"
ln -s "$PWD/dotfiles/gitignore" "$HOME/.gitignore"
ln -s "$PWD/dotfiles/vimrc" "$HOME/.vimrc"
ln -s "$PWD/dotfiles/zshrc" "$HOME/.zshrc"
ln -s "$PWD/dotfiles/zsh_plugins" "$HOME/.zsh_plugins.txt"
echo "🗂️ Dotfiles linked."

# Config Ghostty
GHOSTTY_CONFIG_DIR="$HOME/Library/Application Support/com.mitchellh.ghostty"
mkdir -p "$GHOSTTY_CONFIG_DIR"
rm -f "$GHOSTTY_CONFIG_DIR/config"
ln -s "$PWD/config/ghostty" "$GHOSTTY_CONFIG_DIR/config"
echo "✓ Ghostty configuration linked."

# Reload shell
echo "🔄 Reloading shell..."
exec zsh
